package cc.chordflower.dracpond.application.events;

public enum EventType {
  BEFORE_START,
  BEFORE_ARGUMENT_PARSER,
  AFTER_ARGUMENT_PARSER,
  BEFORE_CONFIG_PARSER,
  AFTER_CONFIG_PARSER,
  AFTER_LOGGING,
  BEFORE_START_VERTX,
  AFTER_START_VERTX,
  BEFORE_STOP_VERTX,
  BEFORE_STOP;
}
